"""Assembly of multiple agents for question answering."""

import copy
import logging

from src.agents.answer import AnswerAgent
from src.agents.coreference import CoreferenceAgent
from src.client.openai_compatible import LLM
from src.shared.logging_config import setup_logging
from src.shared.schemas import OPENAI_MESSAGE, OpenAIDocument

setup_logging(
    log_level="INFO",
)

logger = logging.getLogger(__name__)


class MultiAgentQA:
    """Multi-agent question answering system."""

    def __init__(
        self,
        llm: LLM,
    ) -> None:
        """Multi-agent question answering system.

        Args:
            llm: An instance of the LLM client.

        """
        self.coref_agent = CoreferenceAgent(llm)
        # self.relevance_agent = RelevanceAgent(llm)
        self.answer_agent = AnswerAgent(llm)

    def run(
        self,
        conversation: list[OPENAI_MESSAGE],
        docs: list[OpenAIDocument],
    ) -> str:
        """Run the multi-agent QA pipeline.

        Args:
            conversation: List of messages in the conversation.

        Returns:
            str: Final answer generated by the system.

        """
        conversation = copy.deepcopy(conversation)
        assert conversation[-1]['role'] == 'user'
        conversation[-1]['content'] = self.coref_agent.resolve(conversation)

        # 2. Relevance filtering
        # conversation = self.relevance_agent.filter(conversation)
        # logger.info("After relevance filtering: %s", conversation)

        # 3. Final answer
        return self.answer_agent.answer(conversation, docs)