"""Assembly of multiple agents for question answering."""

import logging

from src.agents.answer import AnswerAgent
from src.agents.coreference import CoreferenceAgent
from src.agents.doc_review import RelevanceAgent
from src.client.openai_compatible import LLM
from src.shared.logging_config import setup_logging
from src.shared.schemas import ExtendedConversation

setup_logging(
    log_level="INFO",
)

logger = logging.getLogger(__name__)


class MultiAgentQA:
    """Multi-agent question answering system."""

    def __init__(
        self,
        llm: LLM,
    ) -> None:
        """Multi-agent question answering system.

        Args:
            llm: An instance of the LLM client.

        """
        self.coref_agent = CoreferenceAgent(llm)
        # self.relevance_agent = RelevanceAgent(llm)
        self.answer_agent = AnswerAgent(llm)

    def run(self, conversation: ExtendedConversation) -> str:
        """Run the multi-agent QA pipeline.

        Args:
            conversation: List of messages in the conversation.

        Returns:
            str: Final answer generated by the system.

        """
        # 0. Initial conversation
        logger.info("Initial conversation: %s", conversation)

        # 1. Coreference resolution
        conversation = self.coref_agent.resolve(conversation)
        logger.info("After coreference resolution: %s", conversation)

        # 2. Relevance filtering
        # conversation = self.relevance_agent.filter(conversation)
        # logger.info("After relevance filtering: %s", conversation)

        # 3. Final answer
        answer = self.answer_agent.answer(conversation)
        logger.info("Final answer: %s", answer)
        return answer
