"""Agent for answering questions using provided documents."""

from datetime import date

from src.client.openai_compatible import LLM
from src.shared.prompts import ANSWER_QUESTION


class AnswerAgent:
    """Agent for answering questions."""

    def __init__(self, llm: LLM) -> None:
        """Initialize the AnswerAgent."""
        self.llm = llm

    def answer(self, conversation: list[dict]) -> str:
        """Generate the final answer based on the conversation.

        Args:
            conversation: List of messages in the conversation.

        Returns:
            str: Final answer generated by the model.

        """
        today = date.today().isoformat()

        documents = [m["content"] for m in conversation if m["role"] == "document"]

        last_user_idx = max(i for i, m in enumerate(conversation) if m["role"] == "user")
        last_user_message = conversation[last_user_idx]["content"]

        documents_block = ""
        if documents:
            documents_block = "\n\nRelevant documents:\n" + "\n".join(
                f"[Document {i + 1}] {doc}" for i, doc in enumerate(documents)
            )

        augmented_user_content = (
            f"{last_user_message}{documents_block}\n\nAnswer the question using only the documents above."
        )

        prompt = [
            {
                "role": "system",
                "content": ANSWER_QUESTION.format(date=today),
            },
            *[m for i, m in enumerate(conversation) if m["role"] != "document" and i < last_user_idx],
            {
                "role": "user",
                "content": augmented_user_content,
            },
        ]

        return self.llm.generate(prompt)
