"""Agent for answering questions using provided documents."""

from datetime import date

from src.client.openai_compatible import LLM
from src.shared.prompts import ANSWER_QUESTION
from src.shared.schemas import ExtendedConversation, OpenAIConversation, OpenAIMessage, extended_to_openai


class AnswerAgent:
    """Agent for answering questions."""

    def __init__(self, llm: LLM) -> None:
        """Initialize the AnswerAgent."""
        self.llm = llm

    def answer(self, conversation: ExtendedConversation) -> str:
        """Generate the final answer based on the conversation.

        Args:
            conversation: List of messages in the conversation.

        Returns:
            str: Final answer generated by the model.

        """
        today = date.today().isoformat()

        openai_conversation = extended_to_openai(conversation.messages)

        prompt = OpenAIConversation(
            [
                OpenAIMessage("system", ANSWER_QUESTION.format(date=today)),
            ]
            + openai_conversation,
        )

        return self.llm.generate(prompt)
