"""Agent for answering questions using provided documents."""

import copy
from datetime import date

from openai.types.chat import ChatCompletionSystemMessageParam

from src.client.openai_compatible import LLM
from src.shared.prompts import ANSWER_QUESTION, DOCUMENT_TEMPLATE
from src.shared.schemas import OPENAI_MESSAGE, OpenAIDocument


class AnswerAgent:
    """Agent for answering questions."""

    def __init__(self, llm: LLM) -> None:
        """Initialize the AnswerAgent."""
        self.llm = llm

    def answer(
        self,
        conversation: list[OPENAI_MESSAGE],
        docs: list[OpenAIDocument],
    ) -> str:
        """Generate the final answer based on the conversation.

        Args:
            conversation: List of messages in the conversation.

        Returns:
            str: Final answer generated by the model.

        """
        today = date.today().isoformat()

        conversation = copy.deepcopy(conversation)
        assert conversation[-1]['role'] == 'user'
        assert isinstance(conversation[-1]['content'], str)
        for doc in docs:
            conversation[-1]['content'] += DOCUMENT_TEMPLATE.format(content=doc.text)

        system_prompt = ChatCompletionSystemMessageParam(
            role="system", content=ANSWER_QUESTION.format(date=today),
        )

        return self.llm.generate([system_prompt] + conversation)
